language: python
git:
  depth: 25
  quiet: true
cache: pip
matrix:
  include:
  - name: "Python 3.7 on Windows (no lint)"
    os: windows
    language: shell
    env:
    - JAVA_HOME="C:\\Program Files\\OpenJDK\\jdk-12.0.2"
    - PATH=/c/Python37:/c/Python37/Scripts:$JAVA_HOME\\bin:$PATH
    before_install:
    - export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
    - choco install wkhtmltopdf
    - choco install python
    - choco install openjdk --version 12.0.2
install:
- set PYTHONIOENCODING=UTF8
- python3 -m pip install --upgrade pip
before_script:
- pip3 install wheel tox
- pip3 install -r requirements.txt
- python3 manage.py makemigrations || python manage.py makemigrations
- python3 manage.py migrate || python manage.py migrate
script:
- if [ "$TRAVIS_OS_NAME" != "windows" ]; then tox -e lint; fi
- python3 manage.py test || python manage.py test
