title: Mobile Security Framework (MobSF)
description: Mobile Security Framework (MobSF) is an automated, all-in-one mobile application (Android/iOS/Windows) pen-testing, malware analysis and security assessment framework capable of performing static and dynamic analysis.
google_analytics: 
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
