title: Mobile Security Framework (MobSF)
description: Mobile Security Framework is an automated, all-in-one mobile application (Android/iOS/Windows) pen-testing framework capable of performing static analysis, dynamic analysis, malware analysis and web API testing.
google_analytics: 
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
