version: '3'
services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: 'password'
  mobsf:
    build:
      dockerfile: Dockerfile.postgres
    ports:
     - "8000:8000"
  
