version: '3'
services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      - PSOTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mobsf
  mobsf:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
     - "8000:8000"
  
